#!/usr/bin/env python3
"""Generate Localizable.xcstrings from plan translations."""
import json
import os

# All 48 keys (no app.name/app.copyright repeated in keys - we have app.name, app.tagline, app.copyright)
# Values per language: en, zh-Hans, zh-Hant, ja, fr, de, es, ko, pt-BR, ru, it, pl, nl
KEYS_ORDER = [
    "app.name", "app.tagline", "app.copyright",
    "selectFile", "noFileSelected", "clickToSelect", "supportedFormats", "compressedFile",
    "searchingDevices", "insertUSB", "selectUSBDevice", "device", "selectFromDropdown",
    "safeToWrite", "proceedWithCaution", "refreshDeviceList",
    "startWrite", "writing", "cancelWrite", "writingProgress", "cancel", "confirm", "error",
    "confirmWriteTitle", "confirmWriteMessage", "confirmWritePrompt", "confirmEraseDevice",
    "eraseWarning", "permanentlyErase", "enterDeviceName",
    "settings.general", "settings.about", "writeOptions", "verifyAfterWrite",
    "showConfirmation", "autoEject", "security", "adminRequired",
    "language.title", "language.display", "language.system",
    "checkUpdates", "menu.tools", "verifyImage",
    "version", "remaining", "speed", "eta", "github", "reportIssue",
]

TRANSLATIONS = {
    "app.name": {"en": "BitLoader", "zh-Hans": "BitLoader", "zh-Hant": "BitLoader", "ja": "BitLoader", "fr": "BitLoader", "de": "BitLoader", "es": "BitLoader", "ko": "BitLoader", "pt-BR": "BitLoader", "ru": "BitLoader", "it": "BitLoader", "pl": "BitLoader", "nl": "BitLoader"},
    "app.tagline": {"en": "Lightweight USB Bootable Drive Creator", "zh-Hans": "轻量级 USB 引导盘制作工具", "zh-Hant": "輕量級 USB 開機碟製作工具", "ja": "軽量USBブータブルドライブ作成ツール", "fr": "Créateur de clé USB bootable léger", "de": "Leichtgewichtiges USB-Boot-Medium-Erstellungstool", "es": "Creador ligero de unidades USB de arranque", "ko": "가벼운 USB 부팅 드라이브 생성 도구", "pt-BR": "Criador de unidade USB inicializável leve", "ru": "Лёгкий инструмент для создания загрузочных USB-накопителей", "it": "Strumento leggero per creare unità USB avviabili", "pl": "Lekkie narzędzie do tworzenia rozruchowych dysków USB", "nl": "Lichtgewicht USB-opstartschijf maker"},
    "app.copyright": {"en": "© 2026 BitLoader", "zh-Hans": "© 2026 BitLoader", "zh-Hant": "© 2026 BitLoader", "ja": "© 2026 BitLoader", "fr": "© 2026 BitLoader", "de": "© 2026 BitLoader", "es": "© 2026 BitLoader", "ko": "© 2026 BitLoader", "pt-BR": "© 2026 BitLoader", "ru": "© 2026 BitLoader", "it": "© 2026 BitLoader", "pl": "© 2026 BitLoader", "nl": "© 2026 BitLoader"},
    "selectFile": {"en": "Select...", "zh-Hans": "选择...", "zh-Hant": "選擇...", "ja": "選択...", "fr": "Sélectionner...", "de": "Auswählen...", "es": "Seleccionar...", "ko": "선택...", "pt-BR": "Selecionar...", "ru": "Выбрать...", "it": "Seleziona...", "pl": "Wybierz...", "nl": "Selecteer..."},
    "noFileSelected": {"en": "No file selected", "zh-Hans": "未选择文件", "zh-Hant": "未選擇檔案", "ja": "ファイル未選択", "fr": "Aucun fichier sélectionné", "de": "Keine Datei ausgewählt", "es": "Ningún archivo seleccionado", "ko": "선택된 파일 없음", "pt-BR": "Nenhum arquivo selecionado", "ru": "Файл не выбран", "it": "Nessun file selezionato", "pl": "Nie wybrano pliku", "nl": "Geen bestand geselecteerd"},
    "clickToSelect": {"en": "Click the button to select an image file", "zh-Hans": "点击右侧按钮选择镜像文件", "zh-Hant": "點擊右側按鈕選擇映像檔", "ja": "右のボタンをクリックしてイメージファイルを選択", "fr": "Cliquez sur le bouton pour sélectionner une image", "de": "Klicken Sie auf die Schaltfläche, um eine Abbilddatei auszuwählen", "es": "Haga clic en el botón para seleccionar un archivo de imagen", "ko": "버튼을 클릭하여 이미지 파일 선택", "pt-BR": "Clique no botão para selecionar um arquivo de imagem", "ru": "Нажмите кнопку для выбора файла образа", "it": "Clicca il pulsante per selezionare un file immagine", "pl": "Kliknij przycisk, aby wybrać plik obrazu", "nl": "Klik op de knop om een imagebestand te selecteren"},
    "supportedFormats": {"en": "Supports ISO, IMG, DMG, ZIP, GZ, XZ, etc.", "zh-Hans": "支持 ISO, IMG, DMG, ZIP, GZ, XZ 等格式", "zh-Hant": "支援 ISO, IMG, DMG, ZIP, GZ, XZ 等格式", "ja": "ISO, IMG, DMG, ZIP, GZ, XZなどに対応", "fr": "Prend en charge ISO, IMG, DMG, ZIP, GZ, XZ, etc.", "de": "Unterstützt ISO, IMG, DMG, ZIP, GZ, XZ usw.", "es": "Soporta ISO, IMG, DMG, ZIP, GZ, XZ, etc.", "ko": "ISO, IMG, DMG, ZIP, GZ, XZ 등 지원", "pt-BR": "Suporta ISO, IMG, DMG, ZIP, GZ, XZ, etc.", "ru": "Поддерживает ISO, IMG, DMG, ZIP, GZ, XZ и др.", "it": "Supporta ISO, IMG, DMG, ZIP, GZ, XZ, ecc.", "pl": "Obsługuje ISO, IMG, DMG, ZIP, GZ, XZ itp.", "nl": "Ondersteunt ISO, IMG, DMG, ZIP, GZ, XZ, etc."},
    "compressedFile": {"en": "Compressed", "zh-Hans": "压缩文件", "zh-Hant": "壓縮檔案", "ja": "圧縮ファイル", "fr": "Compressé", "de": "Komprimiert", "es": "Comprimido", "ko": "압축 파일", "pt-BR": "Compactado", "ru": "Сжатый", "it": "Compresso", "pl": "Skompresowany", "nl": "Gecomprimeerd"},
    "searchingDevices": {"en": "Searching for devices...", "zh-Hans": "正在搜索设备...", "zh-Hant": "正在搜尋裝置...", "ja": "デバイスを検索中...", "fr": "Recherche d'appareils...", "de": "Geräte werden gesucht...", "es": "Buscando dispositivos...", "ko": "장치 검색 중...", "pt-BR": "Procurando dispositivos...", "ru": "Поиск устройств...", "it": "Ricerca dispositivi...", "pl": "Wyszukiwanie urządzeń...", "nl": "Apparaten zoeken..."},
    "insertUSB": {"en": "Please insert a USB device", "zh-Hans": "请插入 USB 设备", "zh-Hant": "請插入 USB 裝置", "ja": "USBデバイスを挿入してください", "fr": "Veuillez insérer un périphérique USB", "de": "Bitte USB-Gerät einstecken", "es": "Por favor, inserte un dispositivo USB", "ko": "USB 장치를 연결하세요", "pt-BR": "Por favor, insira um dispositivo USB", "ru": "Пожалуйста, вставьте USB-устройство", "it": "Inserire un dispositivo USB", "pl": "Podłącz urządzenie USB", "nl": "Steek een USB-apparaat in"},
    "device": {"en": "Device", "zh-Hans": "设备", "zh-Hant": "裝置", "ja": "デバイス", "fr": "Appareil", "de": "Gerät", "es": "Dispositivo", "ko": "장치", "pt-BR": "Dispositivo", "ru": "Устройство", "it": "Dispositivo", "pl": "Urządzenie", "nl": "Apparaat"},
    "selectUSBDevice": {"en": "Select USB device", "zh-Hans": "请选择 USB 设备", "zh-Hant": "請選擇 USB 裝置", "ja": "USBデバイスを選択", "fr": "Sélectionner un périphérique USB", "de": "USB-Gerät auswählen", "es": "Seleccionar dispositivo USB", "ko": "USB 장치 선택", "pt-BR": "Selecionar dispositivo USB", "ru": "Выбрать USB-устройство", "it": "Seleziona dispositivo USB", "pl": "Wybierz urządzenie USB", "nl": "Selecteer USB-apparaat"},
    "selectFromDropdown": {"en": "Select a target device from the dropdown above", "zh-Hans": "请从上方下拉菜单中选择目标设备", "zh-Hant": "請從上方下拉選單中選擇目標裝置", "ja": "上のドロップダウンからターゲットデバイスを選択", "fr": "Sélectionnez un appareil cible dans le menu déroulant", "de": "Wählen Sie ein Zielgerät aus dem Dropdown-Menü", "es": "Seleccione un dispositivo de destino del menú desplegable", "ko": "드롭다운에서 대상 장치 선택", "pt-BR": "Selecione um dispositivo de destino no menu suspenso", "ru": "Выберите целевое устройство из выпадающего списка", "it": "Seleziona un dispositivo di destinazione dal menu a tendina", "pl": "Wybierz urządzenie docelowe z menu rozwijanego", "nl": "Selecteer een doelapparaat uit het dropdown-menu"},
    "safeToWrite": {"en": "Safe to write", "zh-Hans": "可安全写入", "zh-Hant": "可安全寫入", "ja": "安全に書き込み可能", "fr": "Sûr pour l'écriture", "de": "Sicher zum Schreiben", "es": "Seguro para escribir", "ko": "안전하게 쓰기 가능", "pt-BR": "Seguro para gravar", "ru": "Безопасно для записи", "it": "Sicuro da scrivere", "pl": "Bezpieczny do zapisu", "nl": "Veilig om te schrijven"},
    "proceedWithCaution": {"en": "Proceed with caution", "zh-Hans": "请谨慎选择", "zh-Hant": "請謹慎選擇", "ja": "慎重に選択", "fr": "Procéder avec prudence", "de": "Mit Vorsicht fortfahren", "es": "Proceder con precaución", "ko": "주의해서 진행", "pt-BR": "Prossiga com cuidado", "ru": "Действуйте с осторожностью", "it": "Procedere con cautela", "pl": "Postępuj ostrożnie", "nl": "Ga voorzichtig te werk"},
    "refreshDeviceList": {"en": "Refresh Device List", "zh-Hans": "刷新设备列表", "zh-Hant": "重新整理裝置列表", "ja": "デバイスリストを更新", "fr": "Actualiser la liste des appareils", "de": "Geräteliste aktualisieren", "es": "Actualizar lista de dispositivos", "ko": "장치 목록 새로고침", "pt-BR": "Atualizar lista de dispositivos", "ru": "Обновить список устройств", "it": "Aggiorna elenco dispositivi", "pl": "Odśwież listę urządzeń", "nl": "Ververs apparatenlijst"},
    "startWrite": {"en": "Start Writing", "zh-Hans": "开始写入", "zh-Hant": "開始寫入", "ja": "書き込み開始", "fr": "Commencer l'écriture", "de": "Schreiben starten", "es": "Comenzar escritura", "ko": "쓰기 시작", "pt-BR": "Iniciar gravação", "ru": "Начать запись", "it": "Inizia scrittura", "pl": "Rozpocznij zapis", "nl": "Start schrijven"},
    "writing": {"en": "Writing...", "zh-Hans": "写入中...", "zh-Hant": "寫入中...", "ja": "書き込み中...", "fr": "Écriture en cours...", "de": "Schreiben...", "es": "Escribiendo...", "ko": "쓰는 중...", "pt-BR": "Gravando...", "ru": "Запись...", "it": "Scrittura in corso...", "pl": "Zapisywanie...", "nl": "Schrijven..."},
    "cancelWrite": {"en": "Cancel", "zh-Hans": "取消写入", "zh-Hant": "取消寫入", "ja": "キャンセル", "fr": "Annuler", "de": "Abbrechen", "es": "Cancelar", "ko": "취소", "pt-BR": "Cancelar", "ru": "Отмена", "it": "Annulla", "pl": "Anuluj", "nl": "Annuleren"},
    "writingProgress": {"en": "Writing", "zh-Hans": "正在写入", "zh-Hant": "正在寫入", "ja": "書き込み中", "fr": "Écriture", "de": "Schreiben", "es": "Escribiendo", "ko": "쓰는 중", "pt-BR": "Gravando", "ru": "Запись", "it": "Scrittura", "pl": "Zapisywanie", "nl": "Schrijven"},
    "cancel": {"en": "Cancel", "zh-Hans": "取消", "zh-Hant": "取消", "ja": "キャンセル", "fr": "Annuler", "de": "Abbrechen", "es": "Cancelar", "ko": "취소", "pt-BR": "Cancelar", "ru": "Отмена", "it": "Annulla", "pl": "Anuluj", "nl": "Annuleren"},
    "confirm": {"en": "OK", "zh-Hans": "确定", "zh-Hant": "確定", "ja": "OK", "fr": "OK", "de": "OK", "es": "OK", "ko": "확인", "pt-BR": "OK", "ru": "OK", "it": "OK", "pl": "OK", "nl": "OK"},
    "error": {"en": "Error", "zh-Hans": "错误", "zh-Hant": "錯誤", "ja": "エラー", "fr": "Erreur", "de": "Fehler", "es": "Error", "ko": "오류", "pt-BR": "Erro", "ru": "Ошибка", "it": "Errore", "pl": "Błąd", "nl": "Fout"},
    "confirmWriteTitle": {"en": "Confirm Write", "zh-Hans": "确认写入", "zh-Hant": "確認寫入", "ja": "書き込み確認", "fr": "Confirmer l'écriture", "de": "Schreiben bestätigen", "es": "Confirmar escritura", "ko": "쓰기 확인", "pt-BR": "Confirmar gravação", "ru": "Подтвердить запись", "it": "Conferma scrittura", "pl": "Potwierdź zapis", "nl": "Bevestig schrijven"},
    "confirmWriteMessage": {"en": "This will erase all data on %@.", "zh-Hans": "此操作将擦除 %@ 上的所有数据。", "zh-Hant": "此操作將清除 %@ 上的所有資料。", "ja": "%@のすべてのデータが消去されます。", "fr": "Cela effacera toutes les données sur %@.", "de": "Dies löscht alle Daten auf %@.", "es": "Esto borrará todos los datos en %@.", "ko": "%@의 모든 데이터가 삭제됩니다.", "pt-BR": "Isso apagará todos os dados em %@.", "ru": "Это удалит все данные на %@.", "it": "Questo cancellerà tutti i dati su %@.", "pl": "To usunie wszystkie dane z %@.", "nl": "Dit zal alle gegevens op %@ wissen."},
    "confirmWritePrompt": {"en": "Enter device name \"%@\" to confirm:", "zh-Hans": "请输入设备名称「%@」以确认：", "zh-Hant": "請輸入裝置名稱「%@」以確認：", "ja": "確認のためデバイス名「%@」を入力：", "fr": "Entrez le nom de l'appareil « %@ » pour confirmer :", "de": "Geben Sie den Gerätenamen \"%@\" zur Bestätigung ein:", "es": "Ingrese el nombre del dispositivo \"%@\" para confirmar:", "ko": "확인을 위해 장치 이름 \"%@\" 입력:", "pt-BR": "Digite o nome do dispositivo \"%@\" para confirmar:", "ru": "Введите имя устройства \"%@\" для подтверждения:", "it": "Inserisci il nome del dispositivo \"%@\" per confermare:", "pl": "Wpisz nazwę urządzenia \"%@\" aby potwierdzić:", "nl": "Voer de apparaatnaam \"%@\" in om te bevestigen:"},
    "confirmEraseDevice": {"en": "Confirm Erase Device?", "zh-Hans": "确认擦除设备？", "zh-Hant": "確認清除裝置？", "ja": "デバイスの消去確認", "fr": "Confirmer l'effacement de l'appareil ?", "de": "Gerät löschen bestätigen?", "es": "¿Confirmar borrado del dispositivo?", "ko": "장치 삭제 확인?", "pt-BR": "Confirmar apagamento do dispositivo?", "ru": "Подтвердить очистку устройства?", "it": "Conferma cancellazione dispositivo?", "pl": "Potwierdzić usunięcie urządzenia?", "nl": "Apparaat wissen bevestigen?"},
    "eraseWarning": {"en": "This will erase all data on \"%@\".\nThis action cannot be undone.", "zh-Hans": "这将擦除「%@」上的所有数据。\n此操作无法撤销。", "zh-Hant": "這將清除「%@」上的所有資料。\n此操作無法復原。", "ja": "「%@」のすべてのデータが消去されます。\nこの操作は元に戻せません。", "fr": "Cela effacera toutes les données sur « %@ ».\nCette action est irréversible.", "de": "Dies löscht alle Daten auf \"%@\".\nDiese Aktion kann nicht rückgängig gemacht werden.", "es": "Esto borrará todos los datos en \"%@\".\nEsta acción no se puede deshacer.", "ko": "\"%@\"의 모든 데이터가 삭제됩니다.\n이 작업은 취소할 수 없습니다.", "pt-BR": "Isso apagará todos os dados em \"%@\".\nEsta ação não pode ser desfeita.", "ru": "Это удалит все данные на \"%@\".\nЭто действие нельзя отменить.", "it": "Questo cancellerà tutti i dati su \"%@\".\nQuesta azione non può essere annullata.", "pl": "To usunie wszystkie dane z \"%@\".\nTej operacji nie można cofnąć.", "nl": "Dit zal alle gegevens op \"%@\" wissen.\nDeze actie kan niet ongedaan worden gemaakt."},
    "permanentlyErase": {"en": "This will **permanently erase** all data on:", "zh-Hans": "此操作将**永久擦除**以下设备上的所有数据：", "zh-Hant": "此操作將**永久清除**以下裝置上的所有資料：", "ja": "以下のデバイスのすべてのデータを**完全に消去**します：", "fr": "Cela **effacera définitivement** toutes les données sur :", "de": "Dies wird **dauerhaft alle Daten löschen** auf:", "es": "Esto **borrará permanentemente** todos los datos en:", "ko": "다음 장치의 모든 데이터를 **영구적으로 삭제**합니다:", "pt-BR": "Isso **apagará permanentemente** todos os dados em:", "ru": "Это **безвозвратно удалит** все данные на:", "it": "Questo **cancellerà permanentemente** tutti i dati su:", "pl": "To **trwale usunie** wszystkie dane z:", "nl": "Dit zal **permanent alle gegevens wissen** op:"},
    "enterDeviceName": {"en": "Enter device name to confirm:", "zh-Hans": "请输入设备名称以确认：", "zh-Hant": "請輸入裝置名稱以確認：", "ja": "確認のためデバイス名を入力：", "fr": "Entrez le nom de l'appareil pour confirmer :", "de": "Geben Sie den Gerätenamen zur Bestätigung ein:", "es": "Ingrese el nombre del dispositivo para confirmar:", "ko": "확인을 위해 장치 이름 입력:", "pt-BR": "Digite o nome do dispositivo para confirmar:", "ru": "Введите имя устройства для подтверждения:", "it": "Inserisci il nome del dispositivo per confermare:", "pl": "Wpisz nazwę urządzenia aby potwierdzić:", "nl": "Voer de apparaatnaam in om te bevestigen:"},
    "settings.general": {"en": "General", "zh-Hans": "通用", "zh-Hant": "一般", "ja": "一般", "fr": "Général", "de": "Allgemein", "es": "General", "ko": "일반", "pt-BR": "Geral", "ru": "Общие", "it": "Generale", "pl": "Ogólne", "nl": "Algemeen"},
    "settings.about": {"en": "About", "zh-Hans": "关于", "zh-Hant": "關於", "ja": "情報", "fr": "À propos", "de": "Über", "es": "Acerca de", "ko": "정보", "pt-BR": "Sobre", "ru": "О программе", "it": "Info", "pl": "O programie", "nl": "Over"},
    "writeOptions": {"en": "Write Options", "zh-Hans": "写入选项", "zh-Hant": "寫入選項", "ja": "書き込みオプション", "fr": "Options d'écriture", "de": "Schreiboptionen", "es": "Opciones de escritura", "ko": "쓰기 옵션", "pt-BR": "Opções de gravação", "ru": "Параметры записи", "it": "Opzioni di scrittura", "pl": "Opcje zapisu", "nl": "Schrijfopties"},
    "verifyAfterWrite": {"en": "Verify data after writing", "zh-Hans": "写入后验证数据", "zh-Hant": "寫入後驗證資料", "ja": "書き込み後にデータを検証", "fr": "Vérifier les données après l'écriture", "de": "Daten nach dem Schreiben überprüfen", "es": "Verificar datos después de escribir", "ko": "쓰기 후 데이터 검증", "pt-BR": "Verificar dados após a gravação", "ru": "Проверить данные после записи", "it": "Verifica dati dopo la scrittura", "pl": "Weryfikuj dane po zapisie", "nl": "Verifieer gegevens na schrijven"},
    "showConfirmation": {"en": "Show confirmation before writing", "zh-Hans": "写入前显示确认对话框", "zh-Hant": "寫入前顯示確認對話框", "ja": "書き込み前に確認ダイアログを表示", "fr": "Afficher la confirmation avant l'écriture", "de": "Bestätigung vor dem Schreiben anzeigen", "es": "Mostrar confirmación antes de escribir", "ko": "쓰기 전 확인 대화상자 표시", "pt-BR": "Mostrar confirmação antes de gravar", "ru": "Показывать подтверждение перед записью", "it": "Mostra conferma prima della scrittura", "pl": "Pokaż potwierdzenie przed zapisem", "nl": "Toon bevestiging voor schrijven"},
    "autoEject": {"en": "Auto-eject device after writing", "zh-Hans": "写入完成后自动弹出设备", "zh-Hant": "寫入完成後自動退出裝置", "ja": "書き込み完了後にデバイスを自動取り出し", "fr": "Éjecter automatiquement l'appareil après l'écriture", "de": "Gerät nach dem Schreiben automatisch auswerfen", "es": "Expulsar dispositivo automáticamente después de escribir", "ko": "쓰기 완료 후 장치 자동 꺼내기", "pt-BR": "Ejetar dispositivo automaticamente após a gravação", "ru": "Автоматически извлечь устройство после записи", "it": "Espelli automaticamente il dispositivo dopo la scrittura", "pl": "Automatycznie wysuń urządzenie po zapisie", "nl": "Apparaat automatisch uitwerpen na schrijven"},
    "security": {"en": "Security", "zh-Hans": "安全", "zh-Hant": "安全性", "ja": "セキュリティ", "fr": "Sécurité", "de": "Sicherheit", "es": "Seguridad", "ko": "보안", "pt-BR": "Segurança", "ru": "Безопасность", "it": "Sicurezza", "pl": "Bezpieczeństwo", "nl": "Beveiliging"},
    "adminRequired": {"en": "This app requires administrator privileges to write to disk.", "zh-Hans": "此应用需要管理员权限才能写入磁盘。", "zh-Hant": "此應用程式需要管理員權限才能寫入磁碟。", "ja": "このアプリはディスクへの書き込みに管理者権限が必要です。", "fr": "Cette application nécessite des privilèges d'administrateur pour écrire sur le disque.", "de": "Diese App benötigt Administratorrechte zum Schreiben auf die Festplatte.", "es": "Esta aplicación requiere privilegios de administrador para escribir en el disco.", "ko": "이 앱은 디스크에 쓰려면 관리자 권한이 필요합니다.", "pt-BR": "Este aplicativo requer privilégios de administrador para gravar no disco.", "ru": "Для записи на диск этому приложению требуются права администратора.", "it": "Questa app richiede privilegi di amministratore per scrivere sul disco.", "pl": "Ta aplikacja wymaga uprawnień administratora do zapisu na dysku.", "nl": "Deze app heeft beheerdersrechten nodig om naar schijf te schrijven."},
    "language.title": {"en": "Language", "zh-Hans": "语言", "zh-Hant": "語言", "ja": "言語", "fr": "Langue", "de": "Sprache", "es": "Idioma", "ko": "언어", "pt-BR": "Idioma", "ru": "Язык", "it": "Lingua", "pl": "Język", "nl": "Taal"},
    "language.display": {"en": "Display Language", "zh-Hans": "显示语言", "zh-Hant": "顯示語言", "ja": "表示言語", "fr": "Langue d'affichage", "de": "Anzeigesprache", "es": "Idioma de visualización", "ko": "표시 언어", "pt-BR": "Idioma de exibição", "ru": "Язык интерфейса", "it": "Lingua di visualizzazione", "pl": "Język wyświetlania", "nl": "Weergavetaal"},
    "language.system": {"en": "System", "zh-Hans": "跟随系统", "zh-Hant": "跟隨系統", "ja": "システム設定", "fr": "Système", "de": "System", "es": "Sistema", "ko": "시스템", "pt-BR": "Sistema", "ru": "Системный", "it": "Sistema", "pl": "Systemowy", "nl": "Systeem"},
    "checkUpdates": {"en": "Check for Updates...", "zh-Hans": "检查更新...", "zh-Hant": "檢查更新...", "ja": "アップデートを確認...", "fr": "Rechercher des mises à jour...", "de": "Nach Updates suchen...", "es": "Buscar actualizaciones...", "ko": "업데이트 확인...", "pt-BR": "Verificar atualizações...", "ru": "Проверить обновления...", "it": "Controlla aggiornamenti...", "pl": "Sprawdź aktualizacje...", "nl": "Controleer op updates..."},
    "menu.tools": {"en": "Tools", "zh-Hans": "工具", "zh-Hant": "工具", "ja": "ツール", "fr": "Outils", "de": "Werkzeuge", "es": "Herramientas", "ko": "도구", "pt-BR": "Ferramentas", "ru": "Инструменты", "it": "Strumenti", "pl": "Narzędzia", "nl": "Hulpmiddelen"},
    "verifyImage": {"en": "Verify Image...", "zh-Hans": "校验镜像文件...", "zh-Hant": "驗證映像檔...", "ja": "イメージを検証...", "fr": "Vérifier l'image...", "de": "Abbild überprüfen...", "es": "Verificar imagen...", "ko": "이미지 검증...", "pt-BR": "Verificar imagem...", "ru": "Проверить образ...", "it": "Verifica immagine...", "pl": "Weryfikuj obraz...", "nl": "Verifieer image..."},
    "version": {"en": "Version", "zh-Hans": "版本", "zh-Hant": "版本", "ja": "バージョン", "fr": "Version", "de": "Version", "es": "Versión", "ko": "버전", "pt-BR": "Versão", "ru": "Версия", "it": "Versione", "pl": "Wersja", "nl": "Versie"},
    "remaining": {"en": "Remaining", "zh-Hans": "剩余", "zh-Hant": "剩餘", "ja": "残り", "fr": "Restant", "de": "Verbleibend", "es": "Restante", "ko": "남음", "pt-BR": "Restante", "ru": "Осталось", "it": "Rimanente", "pl": "Pozostało", "nl": "Resterend"},
    "speed": {"en": "Speed", "zh-Hans": "速度", "zh-Hant": "速度", "ja": "速度", "fr": "Vitesse", "de": "Geschwindigkeit", "es": "Velocidad", "ko": "속도", "pt-BR": "Velocidade", "ru": "Скорость", "it": "Velocità", "pl": "Prędkość", "nl": "Snelheid"},
    "eta": {"en": "Estimated time remaining", "zh-Hans": "预计剩余时间", "zh-Hant": "預計剩餘時間", "ja": "推定残り時間", "fr": "Temps restant estimé", "de": "Geschätzte verbleibende Zeit", "es": "Tiempo restante estimado", "ko": "예상 남은 시간", "pt-BR": "Tempo restante estimado", "ru": "Осталось времени", "it": "Tempo rimanente stimato", "pl": "Szacowany pozostały czas", "nl": "Geschatte resterende tijd"},
    "github": {"en": "GitHub", "zh-Hans": "GitHub", "zh-Hant": "GitHub", "ja": "GitHub", "fr": "GitHub", "de": "GitHub", "es": "GitHub", "ko": "GitHub", "pt-BR": "GitHub", "ru": "GitHub", "it": "GitHub", "pl": "GitHub", "nl": "GitHub"},
    "reportIssue": {"en": "Report Issue", "zh-Hans": "报告问题", "zh-Hant": "回報問題", "ja": "問題を報告", "fr": "Signaler un problème", "de": "Problem melden", "es": "Informar problema", "ko": "문제 보고", "pt-BR": "Relatar problema", "ru": "Сообщить о проблеме", "it": "Segnala problema", "pl": "Zgłoś problem", "nl": "Meld probleem"},
}

def main():
    strings = {}
    for key in KEYS_ORDER:
        if key not in TRANSLATIONS:
            continue
        locs = {}
        for lang, value in TRANSLATIONS[key].items():
            locs[lang] = {
                "stringUnit": {
                    "state": "translated",
                    "value": value
                }
            }
        strings[key] = {
            "extractionState": "manual",
            "localizations": locs
        }
    catalog = {
        "sourceLanguage": "en",
        "strings": strings,
        "version": "1.0"
    }
    out_path = os.path.join(os.path.dirname(__file__), "..", "BitLoader", "Localizable.xcstrings")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)
    print("Wrote", out_path)

if __name__ == "__main__":
    main()
